---
- hosts: all
  become: yes
  pre_tasks:
  - name: "Install etckeeper"
    apt: name=etckeeper
  roles:
  - role: znzj.ja_jp
  - role: znz.ufw
    ufw_default_forward_policy: reject
    ufw_allow_in_tcp:
    - comment: "HTTP"
      port: 80
    - comment: "HTTPS"
      port: 443
    ufw_allow_out_tcp:
    - comment: "HTTP"
      port: 80
    - comment: "SSH"
      port: 22
    - comment: "SMTPS"
      port: 465
    - comment: "Submission"
      port: 587
    - comment: "IMAPS"
      port: 993
    - comment: "LDAPS"
      port: 636
    - comment: "zabbix-agent"
      port: 10050
    #- comment: "CVS"
    #  port: 2041
    #- comment: "Subversion"
    #  port: 3690
    #- comment: "Git"
    #  port: 9418
    #- comment: "OpenPGP HTTP key server"
    #  port: 11371

  - role: znz.journald
  - role: znz.sshd
  - role: znz.unattended-upgrades
  - role: znz.nadoka
    nadoka:
      - service_name: "fprog"
        irc_host: "{{ nadoka_fprog_irc_host }}"
        irc_port: "{{ nadoka_fprog_irc_port }}"
        irc_pass: "{{ nadoka_fprog_irc_pass }}"
        irc_nick: "User"
        channel_info: "{{ nadoka_fprog_channel_info }}"
        irc_ssl_params: '{}'
      - service_name: "slack"
        irc_host: "{{ nadoka_slack_irc_host }}"
        irc_port: "{{ nadoka_slack_irc_port }}"
        irc_pass: "{{ nadoka_slack_irc_pass }}"
        irc_nick: "{{ nadoka_slack_irc_nick }}"
        channel_info: ''
        irc_ssl_params: '{}'
    when: nadoka_fprog_irc_host is not none and nadoka_fprog_irc_host != ""
  - role: znzj.zabbix
    zabbix_server_conf: |
      StartPingers=3
      Timeout=5
  - role: zabbix
    zabbix_nasne: "{{ local_zabbix_nasne.split(',') }}"
